### ISSUE TITLE
Unable to select text from the slides

### ISSUE THREAD

**Issue by rodrigoprimo** [akrabat/avalanche#8]
It is not possible to select text from the slides.

I notice that if I try to select text from the current slide the text from the next slide is selected.

This doesn't happen with landslide default theme. 

Any ideas?

**Comment by bchhun** [comment]
My fix for issue 10 resolves this one as well. 

It was a matter of using the `z-index` property on the current slide so that it's *over* all the other slides with a `z-index` of 0

**Comment by akrabat** [comment]
Excellent!
